### ISSUE TITLE
Name Column Derive from Display Atttribute

### ISSUE THREAD

**Issue by maharatha** [timabell/ef-enum-to-lookup#45] opened 2016-01-28 06:20 UTC
The Name column should fill up the data that's being used in the Display attribute of the Enum. Currrently it's ignoring it.

Also I find some strange issue of spaces automatically appearing in the name

**Comment by timabell** [comment] 2016-01-30 17:50
> The Name column should fill up the data that's being used in the Display attribute of the Enum. Currrently it's ignoring it.

There's already discussion of adding the display attribute data as a new column, so this is a duplicate of #33 

I'd be interested to know why you need access to this for your particular usage, so please do comment on #33 with some more info.

> Also I find some strange issue of spaces automatically appearing in the name

That's intentional, it's splitting enum value names no CamelCase to make it look nicer. You can turn it off if you like by setting the `SplitWords` property.

https://github.com/timabell/ef-enum-to-lookup/blob/master/EfEnumToLookup/LookupGenerator/EnumToLookup.cs#L37

**Closed by timabell** 2016-01-30 17:50 UTC
